# .readthedocs.yaml
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

# Tell RTD to only build *tags* and not branches
# ensures local builds stay the same.
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py

# This is optional; it controls the *extra downloadable formats*.
formats: []
