package:
  name: rkstiff
  version : 0.0.1

source: 
  git_rev: v0.0.1
  git_url: https://github.com/whalenpt/rkstiff

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - python
    - numpy
    - scipy

test:
  imports:
    - rkstiff

about: 
  home: https://github.com/whalenpt/rkstiff 
  license: MIT License 
  license_file: LICENSE
  summary: "Runge-Kutta adaptive-step solvers for nonlinear PDEs"





