{% set name = "rkstiff" %}
{% set version = "0.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rkstiff-{{ version }}.tar.gz
  sha256: 6fd3ecf8c65c73365acf04001c11712154eb5434eef21219b9595f8b383d4546

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy >=1.14.0
    - python >=3.6
    - scipy >=1.3.2

test:
  imports:
    - rkstiff
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/whalenpt/rkstiff
  summary: Runge-Kutta adaptive-step solvers for nonlinear PDEs
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - whalenpt
