{% set name = "rkstiff" %}
{% set version = "0.0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 6d0778370123f3743619e61e9baa8e98e8771e08af35fc96aea8426d86fc1a23

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - numpy >=1.14.0
    - pip
    - python
    - scipy >=1.3.2
  run:
    - numpy >=1.14.0
    - python
    - scipy >=1.3.2

test:
  imports:
    - rkstiff

about:
  home: "https://github.com/whalenpt/rkstiff"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Runge-Kutta adaptive-step solvers for nonlinear PDEs"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
